### ISSUE TITLE
Server barfs when confronted with invalid JSON table file

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#186]
```
C:\Users\ADRIANHA\Documents\GitHub\testsite [mobileapps-starter +1 ~0 -0 !]> node --debug server.js
Debugger listening on port 5858
In azureMobile.js...
2015-11-12T21:50:11.319Z - verbose: Using SQL Server data source, server: ahall-mobileapps-starter-sql.database.windows.net:default, user: azureadmin@ahall-mobileapps-starter-sql
2015-11-12T21:50:11.319Z - verbose: SQL Azure database detected - setting connection encryption
2015-11-12T21:50:11.319Z - verbose: Using SQL Server data source, server: ahall-mobileapps-starter-sql.database.windows.net:default, user: azureadmin@ahall-mobileapps-starter-sql
2015-11-12T21:50:11.319Z - verbose: SQL Azure database detected - setting connection encryption
module.js:463
    throw err;
    ^

SyntaxError: C:\Users\ADRIANHA\Documents\GitHub\testsite\tables\TaskItem.json: Unexpected string
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:460:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadModule (C:\Users\ADRIANHA\Documents\GitHub\testsite\node_modules\azure-mobile-apps\src\configuration\loader.js:39:24)
    at C:\Users\ADRIANHA\Documents\GitHub\testsite\node_modules\azure-mobile-apps\src\configuration\loader.js:56:13
    at Array.forEach (native)
    at loadDirectory (C:\Users\ADRIANHA\Documents\GitHub\testsite\node_modules\azure-mobile-apps\src\configuration\loader.js:51:32)
C:\Users\ADRIANHA\Documents\GitHub\testsite [mobileapps-starter +1 ~1 -0 !]>
```

**Comment by danderson00** [comment]
This is reasonable behavior. What are you suggesting?
