### ISSUE TITLE
Cannot find query.js after new v2.0.2 install

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#392]
```
Sun Mar 27 2016 20:36:00 GMT+0000 (Coordinated Universal Time): Unaught exception: Error: Cannot find module 'query.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\query\index.js:8:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Explicitly adding query.js to list of project dependencies fixes this.

**Comment by danderson00** [comment]
Agh. This was due to a change of the name in the query.js package.json file. As it was getting query.js from the repo, it consumed the change. I should have used a branch. We'll have to be careful when we make the name change to azure-query-js and publish it to npm.

I've reverted the name back to query.js and all works for now.

**Comment by adrianhall** [comment]
Use a specific commit / tag in the consumption, then you are free to change it.

**Comment by danderson00** [comment]
We will publish it to npm and use that for future. It's existing older versions that are the problem - we can't change the direct reference to git in existing installs. We just have to keep the old repo name alive.
