### ISSUE TITLE
undefined is not a valid identifier during table initialization

### ISSUE THREAD

**Issue by mikejohanson** [Azure/azure-mobile-apps-node#416]
Trying to use the new mobile apps platform pointing to my existing database however I get the following message in stderr from the downloaded logs (since streaming logs doesn't seem to be working in current state). 

```
2016-04-28T05:43:21.416Z - [31merror[39m: Error occurred during table initialization Error: undefined is not a valid identifier. Identifiers must be under 128 characters in length, start with a letter or underscore, and can contain only alpha-numeric and underscore characters.
    at Object.module.exports.validateIdentifier (D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\data\mssql\helpers.js:40:19)
    at Object.module.exports.formatTableName (D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\data\mssql\helpers.js:46:14)
    at Object.module.exports [as updateSchema] (D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\data\mssql\statements\updateSchema.js:8:29)
    at D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\data\mssql\schema.js:46:62
    at process._tickCallback (node.js:366:9)
```
Before the error is: 
```
2016-04-28T05:59:49.008Z - [36mverbose[39m: SQL Azure database detected - setting connection encryption
2016-04-28T05:59:49.856Z - [35msilly[39m: Loaded D:\home\site\wwwroot\tables\Accounts.js
2016-04-28T05:59:49.887Z - [35msilly[39m: Loaded D:\home\site\wwwroot\tables\Accounts.json
2016-04-28T05:59:49.934Z - [35msilly[39m: Loaded D:\home\site\wwwroot\tables\Contacts.js
2016-04-28T05:59:49.965Z - [35msilly[39m: Loaded D:\home\site\wwwroot\tables\Contacts.json
2016-04-28T05:59:49.996Z - [35msilly[39m: Loaded D:\home\site\wwwroot\tables\Tasks.js
2016-04-28T05:59:50.043Z - [35msilly[39m: Loaded D:\home\site\wwwroot\tables\Tasks.json
2016-04-28T05:59:50.043Z - [36mverbose[39m: Adding table definition for Accounts
2016-04-28T05:59:50.090Z - [36mverbose[39m: Adding table definition for Contacts
2016-04-28T05:59:50.121Z - [36mverbose[39m: Adding table definition for Tasks
2016-04-28T05:59:52.322Z - [35msilly[39m: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"Accounts"},{"name":"schema","value":"myschema"}]
2016-04-28T05:59:52.353Z - [32minfo[39m: Updating schema for table Accounts
2016-04-28T05:59:52.369Z - [35msilly[39m: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"Accounts"},{"name":"schema","value":"myschema"}]
```
I've triple checked all the columns, but none of them violate the criteria in the error message above.

Should add that this was working on v2.0.0, i upgraded to 2.1.2 which didn't work, so i rolled back to v2.0.0, but this issue stuck with me.

**Comment by mikejohanson** [comment]
Nevermind....Looks like it was a bad upgrade, I tried upgrading again, and everything is fine. Sorry...

**Comment by danderson00** [comment]
No worries, let us know if it reoccurs!
