### ISSUE TITLE
Validating token with latest jsonwebtoken is failing

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-node#425]
Error: Bad "options.audience" option. The payload already has an "aud" property.
    at D:\home\site\wwwroot\node_modules\jsonwebtoken\sign.js:111:15
    at Array.forEach (native)
    at Object.module.exports [as sign] (D:\home\site\wwwroot\node_modules\jsonwebtoken\sign.js:107:35)
    at Object.sign (D:\home\site\wwwroot\node_modules\azure-mobile-apps\src\auth\index.js:73:24)
    at D:\home\site\wwwroot\api\jwtTokenGenerator.js:16:41
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\home\site\wwwroot\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\home\site\wwwroot\node_modules\express\lib\router\layer.js:95:5)
    at D:\home\site\wwwroot\node_modules\express\lib\router\index.js:277:22

**Comment by joewood** [comment]
Any idea when this will be fixed? It's preventing any login with a JWT.

**Comment by danderson00** [comment]
Sorry, thought I fixed this. Will get a release out soon.

**Comment by joewood** [comment]
Thanks Dale!

**Comment by danderson00** [comment]
Test for this at https://github.com/Azure/azure-mobile-apps-node/blob/master/test/auth/auth.tests.js#L29

**Comment by danderson00** [comment]
@joewood Just released 2.1.6. Let me know if you have any issues!

**Comment by joewood** [comment]
Yes, that fixed it. Thanks for the quick response!
