### ISSUE TITLE
Getting an error when trying to delete an item

### ISSUE THREAD

**Issue by mikejohanson** [Azure/azure-mobile-apps-node#484]
For one of my scripts I have an update/PATCH operation that in the end deletes an object. I'm getting an "undefined is not a function" with the following code when I call the delete function. (I've simplified it a bit to be more concise):

```
table.update(function (context) {
    var item = context.item;
    var invites = context.tables("Invites");
    return invites.where({
        id: item.id
    }).read().then(function (results) {
                //...
                //error is thrown on next line
           return invites.delete({id:results[0].id}).then(function () {
               return context.res.sendStatus(200);
            });
    });
```

I've also tried delete(results[0].id) but that gives me the same error :(
full error: 
```
2016-08-19T04:03:21.300Z - error:  TypeError: undefined is not a function
    at ODataProvider.exports.ODataProvider.ODataProvider.toOData (c:\Azure\node_modules\azure-mobile-apps\node_modules\azure-query-js\lib\ODataProvider.js:69:50)
    at Object.module.exports.toOData (c:\Azure\node_modules\azure-mobile-apps\src\query\index.js:40:38)
    at Object.module.exports [as delete] (c:\Azure\node_modules\azure-mobile-apps\src\data\mssql\statements\delete.js:11:46)
    at Object.module.exports.tableAccess [as delete] (c:\Azure\node_modules\azure-mobile-apps\src\data\mssql\index.js:49:64)
    at processInvite (c:\Azure\tables\Invites.js:283:34)
    at c:\Azure\tables\Invites.js:261:16
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)

```
Thanks for you help,
-Mike

**Comment by danderson00** [comment]
Ahh, this is a bit rough at the moment. You need to pass an actual query object to the delete function:

```
var queries = require('azure-mobile-apps/src/query');
var query = queries.create('Invites').where({ id: results[0].id });
return invites.delete(query).then(
...
```

I added an issue (https://github.com/Azure/azure-mobile-apps-node/issues/485) for simplifying this.

**Comment by mikejohanson** [comment]
Ah ok, got it. Thanks!
